version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: php:7.4
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    environment:
    - VIRTUAL_PORT=80
    - VIRTUAL_HOST=project.local
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: currencies_rates
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
  cron:
    build:
      context: .
      dockerfile: ./docker/cron/Dockerfile
    container_name: cron
    volumes:
      - ./:/var/www